package bataille_navale.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JPanel;

import bataille_navale.Client;
import bataille_navale.Player;

@SuppressWarnings("serial")
public class PanelConnect extends JPanel implements ActionListener
{
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_connect;
    private javax.swing.JLabel l_EnterName;
    private javax.swing.JLabel l_JoinServ;
    private javax.swing.JTextField tf_Username;
    private Client client;
	private MaFrame frame;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form PanelConnect
     */
    public PanelConnect(Client cli, MaFrame framish) {
        frame = framish;
		client  = cli;
    	initComponents();
    	setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // constructeur
    private void initComponents() {

        l_JoinServ = new javax.swing.JLabel();
        l_EnterName = new javax.swing.JLabel();
        b_connect = new javax.swing.JButton();
        b_connect.addActionListener(this);
        tf_Username = new javax.swing.JTextField();

        l_JoinServ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_JoinServ.setText("Rejoindre le serveur de jeu");

        l_EnterName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_EnterName.setText("Entrer votre nom de joueur");

        b_connect.setText("Se connecter");

        tf_Username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf_Username.setText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(l_JoinServ))
                    .addComponent(l_EnterName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_JoinServ)
                .addGap(25, 25, 25)
                .addComponent(l_EnterName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_connect, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(tf_Username))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }
    
	@Override
	public void actionPerformed(ActionEvent e) 
	{
		//Source : BoutonConnect
		if(e.getSource() == b_connect)
		{
			Player play = new Player(tf_Username.getText());
			@SuppressWarnings("unused")
			String validation = client.AddPlayerToServeur(play);
			String[] listMatches = client.GetMatchFromServer();
			//Vérification de la creation du match.
			for(int i = 0; i < listMatches.length; i++)
			{
				System.out.println(listMatches[i]);
			}
			//Changement de panel
			frame.getContentPane().setVisible(false);
			frame.getContentPane().remove(this);
			System.out.println("Go to lobby");
			frame.getContentPane().add(new PanelLobby(client, play, listMatches, frame));
			frame.getContentPane().setVisible(true);
			
		}
	}
}
